---
title: "地球物理数値解析 レポート課題（天野担当分）"
format:
  typst:
    papersize: a4
    mainfont: "Harano Aji Gothic"
    font-paths: fonts
execute:
  freeze: auto
lang: ja
#
# PDFファイルへの変換は以下のコマンドで．
#
# $ quarto render report.qmd --to typst
#
---

```{=typst}
#let blank(n) = box(
  width: 5em,
  height: 1.2em,
  stroke: (thickness: 0.4pt),
  align(center + horizon, text(size: 11pt, fill: luma(50%), [(#n)])),
  baseline: 0.2em,
)
```

- 2026年5月31日の23:59 JST（日本標準時）までにUTOLにPDFファイルをアップロードすること．
- 満点は100点とし，これ以上になった場合には満点とする．ただし，出席点はこれとは別に全体で評価する．

-----

# 課題A （配点：30点）
天野担当分の講義や資料に関する感想を述べよ．


# 課題B （配点：30点）
以下の文章の空欄に入る適切な語句や文，式などを答えよ．

線形移流方程式
$$
\frac{\partial u}{\partial t} + c \frac{\partial u}{\partial x} = 0 \quad (c > 0)
$$
の解析解$u(x, t)$は，初期条件が$u(x, t=0) = u_0(x)$のとき `#blank("B-1")`{=typst} で与えられる．一見すると簡単に解けそうに見えるが，数値的に解くのはそれほど容易なことではない．

以下では$n$番目の時間ステップ，$i$番目の格子点での値を$u_i^n$と書くことにする．有限差分法で，例えば時間方向に1次精度の差分式  `#blank("B-2")`{=typst} を用い，空間方向に2次精度の差分式 `#blank("B-3")`{=typst} を用いると，FTCSスキームは `#blank("B-4")`{=typst} と書くことができる．Taylor展開を用いることでより高精度の差分式を得ることもできるが，高精度の差分式を用いたからといって良いスキームになるとは限らない．実際に，von Neumannの安定性解析を適用すると，このスキームは `#blank("B-5")`{=typst} であることがわかり，実用には適さない．  
同様に安定性解析を適用するとFTBSスキームは `#blank("B-6")`{=typst} ，FTFSスキームは `#blank("B-7")`{=typst} であることがわかる．これらの安定性解析の結果は物理的には `#blank("B-8")`{=typst} と解釈することができ，これは数値流体力学における風上差分法の考え方の基礎となる．  
なお，von Neumannの安定性解析で数値的安定性が保証される場合でも，数値解が必ずしも正確な解を与えるとは限らないことに注意が必要である．例えば，仮に振幅が一定であったとしても，典型的には波長に依存した `#blank("B-9")`{=typst} があらわれ，時間とともに初期の波形が崩れてしまうことがある．また，通常は特に短波長において `#blank("B-10")`{=typst} ため解が鈍ってしまい，シャープな構造を維持することは難しい．安定性と精度はトレードオフの関係にある．

FTCSスキームの安定性について考えるにあたって，最低次の打切り誤差を評価してみると `#blank("B-11")`{=typst} となり，これが実効的な `#blank("B-12")`{=typst} として作用して数値解が発散する原因となることがわかる．FTCSスキームとLax-Wendroffスキームを比較してみると，違いはLax-Wendroffスキームの `#blank("B-13")`{=typst} の項だけであるが，この項が安定性を改善している．Lax-Wendroffスキームは時間・空間ともに2次精度であり，古典的な数値流体力学では実用的に用いられてきたが，急峻な勾配があるときには `#blank("B-14")`{=typst} （オーバーシュート・アンダーシュート）が生じることがよく知られている．これは `#blank("B-15")`{=typst} が示すように2次精度以上の線形のスキームでは避けることができず，スキームに何らかの非線形性を導入することが必要となっている．古典的によく用いられてきたのは `#blank("B-16")`{=typst} であるが，問題に合わせた調整が必要であり，現在ではあまり用いられなくなっている．

Burgers方程式やEuler方程式などの双曲型偏微分方程式の多くは保存形で書くことができる．したがって，これらの方程式を解くための数値スキームについても保存形が用いられることが多い．離散的な保存形は基礎方程式を `#blank("B-17")`{=typst} することで得られる．保存形の数値スキームを使うと，境界条件の影響を除いて `#blank("B-18")`{=typst} という好ましい性質がある．

非線形の双曲型偏微分方程式を考えるときに重要となるのが特性曲線の考え方である．特性速度 $\lambda(x)$ に沿ってある物理量 $J$ が一定となるとき，この $J$ を `#blank("B-19")`{=typst} と呼ぶ．特性曲線は$x-t$の空間で，特性速度で定義される微分方程式 `#blank("B-20")`{=typst} の解である．線形移流方程式では$\lambda(x)$は `#blank("B-21")`{=typst} ，$J$ は `#blank("B-22")`{=typst} である．線形移流方程式では異なる初期条件からスタートする特性曲線が交わることはないが，Burgers方程式のような非線形の方程式では特性曲線が交わることがある．このような場合，特性曲線の交点で `#blank("B-23")`{=typst} となるため，数学的に一意な解が存在せず，有限の粘性項（拡散項）が必要となる．同様のことは流体力学のEuler方程式においても成り立ち，有限振幅の音波は有限時間で `#blank("B-24")`{=typst} に発展する．実用的な数値スキームには（陰に陽に）人工的な `#blank("B-25")`{=typst} が含まれているため，陽に粘性を含まない方程式であってもこのような数値解を安定に得ることができる．

保存形の数値スキームを用いるとき，数値解が収束するならば元の微分方程式の `#blank("B-26")`{=typst} に収束することが保証される．これが圧縮性数値流体力学で保存形のスキームが好まれる理由である．ただし，収束する解が `#blank("B-27")`{=typst} を満たす物理的な解であるとは限らないので注意が必要である．

複数の独立変数に対する非線形双曲型偏微分方程式を考えるとき，特性速度は独立変数の数だけ存在する．例えば，Euler方程式について考えると，$(\rho, v, p)$の3つの独立変数があるため，3つの特性速度$\lambda_1 < \lambda_2 < \lambda_3$が存在するが，これらは物理的には `#blank("B-28")`{=typst} ， `#blank("B-29")`{=typst} ，`#blank("B-30")`{=typst} に対応する．

# 課題C （配点：40点）
Euler方程式を始めとする多変数の非線形双曲型偏微分方程式の数値解法を設計するにあたって，線形移流方程式の数値解法，特に風上差分法の考え方がどのように生かされるか，講義内容から自身で理解できた範囲で（もしくは講義以前に既知の事項があればそれも含めて）議論せよ．講義では理解できなかった点，自身の中で理解が不十分な点についても述べること．

議論には例えば以下の語句を用いると良い．

- 特性速度
- 特性変数（Riemann不変量）
- ヤコビアン
- 固有値・固有ベクトル
- 対角化
- Riemann問題


# 課題D （配点：70点）
## 1.
線形移流方程式の数値解を1次精度風上差分法およびLax-Wendroff法を用い，数値実験結果から誤差$\epsilon$がそれぞれ理論的に予想される$\epsilon \propto (\Delta x)^1$および$\epsilon \propto (\Delta x)^2$となることを示せ．なお，計算領域は$0 \leq x \leq 1$，境界条件は周期境界条件，初期条件は
$$
u(x) = \sin \left ( 2 \pi x \right)
$$
とする．ただし，$t = 1$における数値解と解析解の差から
$$
\epsilon =
\sqrt{ \int \vert u(x) - u_{\mathrm{analytic}}(x) \rvert^2 dx} =
\sqrt{ \sum_{i} \lvert u_{i}^{n} - u_{\mathrm{analytic}}(x_i) \rvert^2 \Delta x}
$$
を誤差と定義しよう．もちろん$\Delta x$を小さくとるには$\Delta t$も小さくしなければならないので，$t = 1$まで計算するのに必要なステップ数が増えることに注意せよ．少なくとも1桁以上は$\Delta x$を変化させて，$\epsilon$と$\Delta x$の関係を両対数でプロットすること．

## 2.
以下の初期条件のもとで非粘性Burgers方程式の数値解を1次精度風上差分法および2段階Lax-Wendroff法（人工粘性あり）を用いて求め，両者を比較・考察せよ．
計算領域は$-1 \leq x \leq +1$，境界条件は周期境界条件，初期条件は
$$
u(x) =
\begin{cases}
& 0 \quad -1 < x < -\frac{1}{3} \\
& 1 \quad -\frac{1}{3} < x < +\frac{1}{3} \\
& 0 \quad +\frac{1}{3} < x < 1 \\
\end{cases}
$$
とする．

## 3.
1次元Euler方程式について，正方向，負方向に伝播する有限振幅の音波の固有モードをそれぞれ初期条件に選んだときの時間発展を2段階Lax-Wendroff法によって数値的に求めよ．それぞれの場合について振幅依存性を考察すること．ただし，初期条件としてある伝播方向（正または負）を選んだ際には，それ以外のモード（逆方向に伝播する音波およびエントロピー波）の振幅は0となるように注意せよ．また，境界条件は周期境界条件を用いること．

## 4.
1次元Euler方程式についてのRiemann問題
$$
(\rho, v, p) =
\begin{cases}
& (\rho_L, v_L, p_L) \quad x < 0.5 \\
& (\rho_R, v_R, p_R) \quad x > 0.5 \\
\end{cases}
$$
を考えよう．ただし全ての問題で $\gamma = 1.4$ ，計算領域は $0 \leq x \leq 1$，境界条件は全ての物理量に対して $\partial/\partial x = 0$ とする．

以下の5つの標準テスト問題を数値的に解き，スキームの性質を考察せよ．ただし各問題の計算終了時刻の目安を $T$ とする．

数値スキームは任意とするが，例えば2段階Lax-Wendroff法（人工粘性あり）を用いる場合は，人工粘性係数や，グリッド数などのパラメータに対する依存性を調べてみると良いだろう．
なお，問題2では真空に近い領域が発生すること，問題3や問題5では非常に強い衝撃波が発生することから，安定に数値解を求めるのは難しいことが予想される．うまくいかなかった場合であっても，初期条件を少し調節するなどして，その理由を考察してみてほしい．


| 問題  | $\rho_L$ | $v_L$ | $p_L$ | $\rho_R$ | $v_R$ | $p_R$ | $T$ |
|-------|----------|-------|-------|----------|-------|-------|---------|
| $1$   | $1.0$ | $0.0$ | $1.0$ | $0.125$ | $0.0$ | $0.1$ | $0.2$ |
| $2$   | $1.0$ | $-2.0$ | $0.4$ | $1.0$ | $+2.0$ | $0.4$ | $0.15$ |
| $3$   | $1.0$ | $0.0$ | $1000$ | $1.0$ | $0.0$ | $0.01$ | $0.012$ |
| $4$   | $5.99924$ | $19.5975$ | $460.894$ | $5.99242$ | $-6.19633$ | $46.0950$ | $0.035$ |
| $5$   | $1.0$ | $-19.5975$ | $1000$ | $1.0$ | $-19.5975$ | $0.01$ | $0.012$ |
