project:
  output-dir: docs
  render:
    - introduction.qmd
    - chap01.qmd
    - chap02.qmd
    - chap03.qmd
    - chap04.qmd
  preview:
    port: 4200
    watch-inputs: true

execute:
  freeze: auto